# -*- makefile -*- : Force emacs to use Makefile mode

# Linker script
#
LDSCRIPT = arch/i386/scripts/linux.lds

# Compiler flags for building host API wrapper
#
LINUX_CFLAGS	+= -m32

# Include generic Linux Makefile
#
MAKEDEPS += arch/x86/Makefile.linux
include arch/x86/Makefile.linux
