# -*- makefile -*- : Force emacs to use Makefile mode

# The EFI linker script
#
LDSCRIPT	= arch/x86/scripts/efi.lds

# Retain relocation information for elf2efi
#
LDFLAGS		+= -q -S

# Media types.
#
NON_AUTO_MEDIA	+= efi

# Rule for building EFI files
#
$(BIN)/%.efi : $(BIN)/%.efi.tmp $(ELF2EFI32)
	$(QM)$(ECHO) "  [FINISH] $@"
	$(Q)$(ELF2EFI32) $< $@
