# -*- makefile -*- : Force emacs to use Makefile mode

# Starting virtual address
#
LDFLAGS += -Ttext=0x120000000

# Include generic Linux Makefile
#
MAKEDEPS += Makefile.linux
include Makefile.linux
