# -*- makefile -*- : Force emacs to use Makefile mode

# Starting virtual address
#
LDFLAGS += -Ttext=0x400000

# Include generic Linux Makefile
#
MAKEDEPS += arch/arm/Makefile.linux
include arch/arm/Makefile.linux
