# -*- makefile -*- : Force emacs to use Makefile mode

# Set base virtual address to 0xeb000000
#
# This is aligned to a 4MB boundary and so allows 4MB megapages to be
# used to map the iPXE binary.  The address pattern is also easily
# recognisable if leaked to unexpected contexts.
#
LDFLAGS		+= --section-start=.prefix=0xeb000000

# Include generic SBI Makefile
#
MAKEDEPS	+= arch/riscv/Makefile.sbi
include arch/riscv/Makefile.sbi
