# -*- makefile -*- : Force emacs to use Makefile mode

# Specify EFI image builder
#
ELF2EFI		= $(ELF2EFI32)

# Include generic EFI Makefile
#
MAKEDEPS	+= arch/riscv/Makefile.efi
include arch/riscv/Makefile.efi
