# -*- makefile -*- : Force emacs to use Makefile mode

# Place .textdata in negative 2GB of address space
#
CFLAGS		+= -mcmodel=kernel
LDFLAGS		+= --section-start=.textdata=0xffffffffeb000000

# Assembly code does not respect a red zone.
#
CFLAGS		+= -mno-red-zone

# Generate extra space for page tables to cover .textdata
#
LDFLAGS		+= --defsym=_use_page_tables=1

# Include generic BIOS Makefile
#
MAKEDEPS	+= arch/x86/Makefile.pcbios
include arch/x86/Makefile.pcbios
