/** @file
 *
 * "ro" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "ro" basic remapping */
static struct keymap_key ro_basic[] = {
	{ 0, 0 }
};

/** "ro" AltGr remapping */
static struct keymap_key ro_altgr[] = {
	{ 0, 0 }
};

/** "ro" keyboard map */
struct keymap ro_keymap __keymap = {
	.name = "ro",
	.basic = ro_basic,
	.altgr = ro_altgr,
};
