/** @file
 *
 * "sr-latin" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "sr-latin" basic remapping */
static struct keymap_key sr_latin_basic[] = {
	{ 0xdc, 0x3c },	/* Pseudo-'\\' => '<' */
	{ 0xfc, 0x3e },	/* Pseudo-'|' => '>' */
	{ 0, 0 }
};

/** "sr-latin" AltGr remapping */
static struct keymap_key sr_latin_altgr[] = {
	{ 0, 0 }
};

/** "sr-latin" keyboard map */
struct keymap sr_latin_keymap __keymap = {
	.name = "sr-latin",
	.basic = sr_latin_basic,
	.altgr = sr_latin_altgr,
};
