/** @file
 *
 * "il" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "il" keyboard mapping */
struct key_mapping il_mapping[] __keymap = {
	{ 0x1d, 0x1b },	/* 0x1d => 0x1b */
	{ 0x27, 0x2c },	/* '\'' => ',' */
	{ 0x28, 0x29 },	/* '(' => ')' */
	{ 0x29, 0x28 },	/* ')' => '(' */
	{ 0x2f, 0x2e },	/* '/' => '.' */
	{ 0x3c, 0x3e },	/* '<' => '>' */
	{ 0x3e, 0x3c },	/* '>' => '<' */
	{ 0x5b, 0x5d },	/* '[' => ']' */
	{ 0x5d, 0x5b },	/* ']' => '[' */
	{ 0x60, 0x3b },	/* '`' => ';' */
	{ 0x7b, 0x7d },	/* '{' => '}' */
	{ 0x7d, 0x7b },	/* '}' => '{' */
	{ 0xdc, 0x3c },	/* Pseudo-'\\' => '<' */
	{ 0xfc, 0x3e },	/* Pseudo-'|' => '>' */
};
