/** @file
 *
 * "us" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "us" basic remapping */
static struct keymap_key us_basic[] = {
	{ 0, 0 }
};

/** "us" keyboard map */
struct keymap us_keymap __keymap = {
	.name = "us",
	.basic = us_basic,
};
