/** @file
 *
 * "sr-latin" keyboard mapping
 *
 * This file is automatically generated; do not edit
 *
 */

FILE_LICENCE ( PUBLIC_DOMAIN );

#include <ipxe/keymap.h>

/** "sr-latin" keyboard mapping */
struct key_mapping sr_latin_mapping[] __keymap = {
};
